name: SurvivalDebugStick
version: '${project.version}'
main: de.janschuri.SurvivalDebugStick.SurvivalDebugStick
api-version: '1.19'
depend:
  - LunaticLib
commands:
  survivaldebugstick:
    description: Get the survival debug stick and reload the config.
    permission: survivaldebugstick.admin